[tool.system]
streamlit = "12.7.0"

[server]
port = 8501
cookieSecret = "a-random-key-appears-here"

[theme]
primaryColor = "#006FFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0e2b6e"
font = "Poppins"

[client]
showErrorDetails = true
toolbarMode = "auto"

[browser]
gatherUsageStats = true
serverAddress = "localhost"
serverPort = 8501

[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true
dataFrameSerialization = "arrow"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[mapbox]
token = ""

[runner]
magicEnabled = true
fixMatplotlib = true
fastReruns = true
runOnSave = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
