[tool.system]
streamlit = "12.7.0"

[server]
port = 8501

[theme]
primaryColor = "#006FFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0a0a36"

[client]
showErrorDetails = false
toolbarMode = "auto"

[browser]
gatherUsageStats = true
serverAddress = "localhost"
serverPort = 8501

[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true
dataFrameSerialization = "arrow"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[mapbox]
token = ""

[runner]
magicEnabled = true
fixMatplotlib = true
fastReruns = true
runOnSave = true
enableCORS = false
