[server]
port = 8501
cookieSecret = "a-random-key-appears-here"

[theme]
primaryColor = "#FFFFFF"
secondaryBackgroundColor = "#AFE1AF"
textColor = "#0B6122"
font =" Poppins"

[client]
showErrorDetails = true
toolbarMode = "auto"

[browser]
gatherUsageStats = true
serverAddress = "localhost"
serverPort = 8501

[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true
dataFrameSerialization = "arrow"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[mapbox]
token = ""

[runner]
magicEnabled = true
fixMatplotlib = true
fastReruns = true
runOnSave = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
